theme: minima
title: DNS notes
author: Elliott Robinson
description: My notes on the "Cricket book": DNS and BIND, 5th Edition, by Cricket Liu and Paul Albitz. Copyright 2006, O'Reilly Media, Inc., 0-596-10057-4
